###
# Defines infrastructure for testing
##

version: '3'

services:

  client:
    build: ./client
    environment:
      hostname: server
      username: root
    volumes:
      - ./.keys/key_rsa:/root/.ssh/id_rsa
      - ../scripts:/opt/resources
      - ./client/.data:/data
    links:
      - server
    depends_on:
      - server
  # app

  server:
    build: ./server
    volumes:
      - ./.keys/key_rsa.pub:/root/.ssh/authorized_keys
      - ./server/.data:/data
  # server

# docker-compose
